spring:
  profiles:
    active:
      -dev
---
spring:
  profiles: dev
  application:
    name: consumer-server
server:
  port: 80

feign:
  hystrix:
    enabled: true

eureka:
  client:
    register-with-eureka: false
    service-url:
      #单机
      defaultZone: http://localhost:8021/eureka
      #集群
#      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/
#  instance:
#      instance-id: consumer-server-80
#      prefer-ip-address: true
