spring:
  profiles:
    active:
      -dev

---
spring:
   profiles: dev
   application:
    name: monitor-server
    
server:
  port: 8031
eureka:
  client:
    register-with-eureka: false
    service-url:
      #单机
      defaultZone: http://localhost:8021/eureka
      #集群
#      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/
