spring:
  profiles:
    active:
      -dev

---
spring:
   profiles: dev
   application:
    name: registry-service
    
server:
  port: 7001

eureka:
  server:
    enable-self-preservation: true  #自我保护配置默认为true
  instance:
    hostname: localhost #eureka服务端的实例名称
  client:
    register-with-eureka: false     #false表示不向注册中心注册自己。
    fetch-registry: false     #false表示自己端就是注册中心，我的职责就是维护服务实例，并不需要去检索服务
    service-url:
      #单机
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/       #设置与Eureka Server交互的地址查询服务和注册服务都需要依赖这个地址（单机）。

---
service:
  port: 8202
spring:
  profiles: test
  application:
    name: registry-service
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8080/eureka
