spring:
  profiles:
    active:
      -dev

---
spring:
   profiles: dev
   application:
    name: test-api
    
server:
  port: 8001

eureka:
  client:
    service-url:
      #单机
      defaultZone: http://localhost:7001/eureka
      #集群
#      defaultZone: http://localhost:7001/eureka,http://eureka7002.com:7002/eureka/
  instance:
    instance-id: servcie-8001-hystrix
    prefer-ip-address: true

info:
  app.name: abcdefg
  company.name: xxxx


# springcloud 中使用 hystrix-dashboard 进行监控的时候启动报错
# path:/actuator/hystrix.stream, status : 404, error : Not Found”
# 这是因为springboot2.x使用了endpoint
management:
  endpoints:
    web:
      exposure:
#        include: ["hystrix-stream"]
        include: "*"
